services:
  db:
    image: postgres:15
    container_name: ihealth_db
    environment:
      POSTGRES_USER: ihealth_user
      POSTGRES_PASSWORD: ihealth_pass
      POSTGRES_DB: ihealth
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ihealth_user -d ihealth"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ihealth.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"

  web:
    image: php:8.1-apache
    container_name: ihealth_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - DB_HOST=db
      - DB_NAME=ihealth
      - DB_USER=ihealth_user
      - DB_PASSWORD=ihealth_pass
      - DB_PORT=5432
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y libpq-dev postgresql-client &&
      docker-php-ext-install pdo pdo_pgsql &&
      a2enmod rewrite &&
      chown -R www-data:www-data /var/www/html &&
      echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
      a2ensite 000-default &&
      pkill -9 apache2 || true &&
      exec apache2-foreground"
volumes:
  postgres_data: